---
- name: ensure required packages are installed
  become: true
  apt: name={{item}} state=present
  with_items:
  - chromium
  - tigervnc-standalone-server
  - libjpeg62-turbo-dev
  - zlib1g-dev
  - gcc
  - python3-dev
  - python3-dbg
  - xfonts-base
  - fonts-arphic-bkai00mp
  - fonts-arphic-bsmi00lp
  - fonts-arphic-gbsn00lp
  - fonts-arphic-gkai00mp
  - fonts-arphic-ukai
  - fonts-farsiweb
  - fonts-nafees
  - fonts-sil-abyssinica
  - fonts-sil-ezra
  - fonts-sil-padauk
  - fonts-unfonts-extra
  - fonts-unfonts-core
  - fonts-indic
  - fonts-thai-tlwg
  - fonts-lklug-sinhala

- name: mkdir /etc/service/{Xvnc,vnc-websock,brozzler-worker}
  file:
    path: '/etc/service/{{item}}'
    state: directory
  with_items:
  - Xvnc
  - vnc-websock
  - brozzler-worker
  become: true

- name: install /etc/service/Xvnc/run
  template:
    src: templates/Xvnc-run.j2
    dest: /etc/service/Xvnc/run
    mode: 0755
  notify:
  - restart Xvnc
  become: true

- name: mkdir {{venv_root}}/websockify-ve3
  become: true
  file: path={{venv_root}}/websockify-ve3 state=directory owner={{user}}
 
#get python3 version for checks below 
- shell: "python3 --version"
  register: python_installed
  
 #websockify's dependency numpy's latest version no longer supports 3.5
- name: install old version of numpy for websockify
  pip:
    name: numpy==1.18.4
    virtualenv: '{{venv_root}}/websockify-ve3'
    virtualenv_python: python3
    virtualenv_command: python3 -mvirtualenv
    extra_args: '--no-input --upgrade --pre --cache-dir=/tmp/pip-cache'
  become: true
  become_user: '{{user}}'
  when: '"Python 3.5" in python_installed.stdout'
 
- name: install websockify in virtualenv
  pip:
    name: git+https://github.com/kanaka/websockify.git#egg=websockify
    virtualenv: '{{venv_root}}/websockify-ve3'
    virtualenv_python: python3
    virtualenv_command: python3 -mvirtualenv
    extra_args: '--no-input --upgrade --pre --cache-dir=/tmp/pip-cache'
  become: true
  become_user: '{{user}}'

- name: install /etc/service/vnc-websock/run
  template:
    src: templates/vnc-websock-run.j2
    dest: /etc/service/vnc-websock/run
    mode: 0755
  notify:
  - restart vnc-websock
  become: true

- name: mkdir {{venv_root}}/brozzler-ve3
  become: true
  file: path={{venv_root}}/brozzler-ve3 state=directory owner={{user}}

- name: install brozzler in virtualenv
  pip:
    name: '{{brozzler_pip_name}}'
    virtualenv: '{{venv_root}}/brozzler-ve3'
    virtualenv_python: python3
    virtualenv_command: python3 -mvirtualenv
    extra_args: '--no-input --upgrade --pre --cache-dir=/tmp/pip-cache'
  become: true
  become_user: '{{user}}'
  notify:
  - restart brozzler-worker

- name: install /etc/service/brozzler-worker/run
  template:
    src: templates/brozzler-worker-run.j2
    dest: /etc/service/brozzler-worker/run
    mode: 0755
  notify:
  - restart brozzler-worker
  become: true

